In [1]:
import pandas as pd
df = pd.read_csv('retail_sales_dataset.csv')
df

,Transaction ID,Date,Customer ID,Gender,Age,Product Category,Quantity,Price per Unit,Total Amount
0,1,2023-11-24,CUST001,Male,34,Beauty,3,50,150
1,2,2023-02-27,CUST002,Female,26,Clothing,2,500,1000
2,3,2023-01-13,CUST003,Male,50,Electronics,1,30,30
3,4,2023-05-21,CUST004,Male,37,Clothing,1,500,500
4,5,2023-05-06,CUST005,Male,30,Beauty,2,50,100
...,...,...,...,...,...,...,...,...,...
995,996,2023-05-16,CUST996,Male,62,Clothing,1,50,50
996,997,2023-11-17,CUST997,Male,52,Beauty,3,30,90
997,998,2023-10-29,CUST998,Female,23,Beauty,4,25,100
998,999,2023-12-05,CUST999,Female,36,Electronics,3,50,150
999,1000,2023-04-12,CUST1000,Male,47,Electronics,4,30,120

In [3]:
df.describe()

       Transaction ID         Age     Quantity  Price per Unit  Total Amount
count     1000.000000  1000.00000  1000.000000     1000.000000   1000.000000
mean       500.500000    41.39200     2.514000      179.890000    456.000000
std        288.819436    13.68143     1.132734      189.681356    559.997632
min          1.000000    18.00000     1.000000       25.000000     25.000000
25%        250.750000    29.00000     1.000000       30.000000     60.000000
50%        500.500000    42.00000     3.000000       50.000000    135.000000
75%        750.250000    53.00000     4.000000      300.000000    900.000000
max       1000.000000    64.00000     4.000000      500.000000   2000.000000

In [4]:
usecols=['Quantity','Price per Unit','Age']

In [19]:
from sklearn.model_selection import train_test_split
x_train,x_test, y_train,y_test = train_test_split(df[['Age',"Price per Unit"]], df[['Quantity']], test_size = 0.33,random_state=0)

In [10]:
from sklearn import preprocessing
x_train_norm=preprocessing.normalize(x_train)
x_test_norm=preprocessing.normalize(x_test)

In [11]:
from sklearn.cluster import KMeans
exercise=KMeans(n_clusters=3,random_state=0,n_init=10)
exercise.fit(x_test_norm)

KMeans(n_clusters=3, random_state=0)

In [20]:
import seaborn as sns
sns.scatterplot(df=x_train,x='Age',y='Quantity',hue=exercise.labels_)
plt.show()

ValueError: Could not interpret value `Age` for parameter `x`

In [17]:
sns.boxplot(x=exercise.labels_,y=y_train['Price_per_Unit'])
plt.show()

KeyError: 'Price_per_Unit'